gcp_project_id      = "serverless-face-recognition"
gcp_region          = "us-central1"
bucket_name         = "face-images-gcp-comparison"
firestore_database  = "(default)"
pubsub_topic_name   = "face-registration-topic"